[project]
name = "lingjun"
version = "0.1.0"
description = ""
authors = [{ name = "lzl", email = "lzlworksharder@163.com" }]
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "polars",
    "scikit-learn",
    "numpy",
    "pandas",
    "matplotlib",
    "tqdm",
    "wandb",
    "python-dotenv",
    "kaggle",
    "grpcio",
    "pyarrow",
    "pytz",
    "torch>=2.5.1,<2.6.0",
    "torch_optimizer",
    "nvidia-cuda-nvrtc-cu12<12.9",
    "ipykernel",
    "xgboost",
    "omegaconf",
    "transformers",
    "ipywidgets",
    "jupyter",
    "accelerate>=1.13.0",
    "tensorboard>=2.20.0",
]

[project.optional-dependencies]
dev = [
    "ipykernel",
]

[tool.hatch.build.targets.wheel]
packages = ["src"]

[[tool.uv.index]]
url = "http://mirrors.aliyun.com/pypi/simple"
default = true

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
